name: Update Postcard

on:
  schedule:
    - cron:  '0 7 1 * *'

jobs:
  build:
    strategy:
      matrix:
        platform: [windows-latest]
        r-version: ['4.0.2']
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.r-version }}
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Update Postcard
        run: |
          source("renv/activate.R")
          renv::restore()
          rmarkdown::render("index.Rmd")
        shell: Rscript {0}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update Postcard
          delete-branch: true
